### PR TITLE
Use udp to transmit messages

### PR DESCRIPTION
**Pull request by hacpy**

### CODE REVIEW

**Comment by hacpy** [comment]
The first step is already stuck.

**Comment by hacpy** [comment]
Wait and see if there is still a rescue.

**Review by rjman-ljm — APPROVED** [review]
Looks overall good, and the conflict was also well resolved.

**Comment by rjman-ljm** [comment]
The server was already access，
`./start_game.sh user 47.97.212.163.6666`
And you can log in to the server as the user of `hacpy` to restart the service of program server

**Comment by hacpy** [comment]
unnamed

**Comment by hacpy** [comment]
Details about the transmitted messages will be expanded in the next pr.

**Pull request merged**
