### PR TITLE
Detects players correctly and displays them in the lobby

### PR DESCRIPTION
**Pull request by hacpy**
For #19.

### CODE REVIEW

**Comment by hacpy** [comment]
I hope there is a normal start game prelude.

**Comment by rjman-ljm** [comment]
The character has been successfully load, and the next step is to try displaying it on the UI

**Comment by hacpy** [comment]
> The character has been successfully load, and the next step is to try displaying it on the UI #18

kyd, kzbc. But I think I will load a default avatar UI when the user enters the lobby. I'll do a dynamic load when the selector screen is refined again, but it should be in the next pr. Of course, if you have more energy you can try to implement a selection of avatars.

**Comment by hacpy** [comment]
Why can't you get the client's information in the state? Shouldn't the game data be loaded when you open the program?

**Comment by rjman-ljm** [comment]
> Why can't you get the client's information in the state? Shouldn't the game data be loaded when you open the program?

I think this is OK, now perhaps [already] (https://github.com/Rustops/no-name-card-game/blob/check-player/client/src/states/loading.rs#L162) can read the user's settings, if you want to complete the function of loading user information, you can improve this code.
The initial startup requires the user to enter information such as a user name, which will be saved to the cache file, and starting again (or later) only needs to be loaded from the cache

**Pull request merged**
